title: Nina Gumatay Diaz Curriculam Vitae 
logo: /assets/img/Professional UM Headshot Toppel Center.jpg
description: Nina Gumatay Diaz Academic CV 2024-2025 
show_downloads: false
google_analytics: 
theme: jekyll-theme-minimal
